"""add restaurant id to food category

Revision ID: 11942d2d6c97
Revises: 7277acc8f603
Create Date: 2026-10-05 13:01:27.688720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11942d2d6c97'
down_revision: Union[str, Sequence[str], None] = '7277acc8f603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_category', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_food_category_restaurant_id'), 'food_category', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'food_category', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_category', type_='foreignkey')
    op.drop_index(op.f('ix_food_category_restaurant_id'), table_name='food_category')
    op.drop_column('food_category', 'restaurant_id')
    # ### end Alembic commands ###
