"""create_update_resturant_True

Revision ID: 14f425cca4dd
Revises: 11942d2d6c97
Create Date: 2026-10-05 13:10:00.733255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f425cca4dd'
down_revision: Union[str, Sequence[str], None] = '11942d2d6c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_category', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_category', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
